### ISSUE TITLE
More details needed on search results data

### ISSUE THREAD

**Issue by Shomegie** [gm-io/spoilers#3]
### ISSUE: Returned Data from Search Route 

**Summary:**
Search results for media with similar names, 'and',  without posters, are not distinguishable from each other. More information needed (such as director name) to add uniqueness to returned data. 

Also search results contain 'person' objects which are not in scope of what is to be displayed and thus produce 'undefined' display thumbnails and error 404 when clicked.

**Steps to Reproduce for media with similar names and no poster-images:**
1. Search the term 'sleep' in the search bar of application
2. View displayed results
3. Multiple titles with the name 'sleep' and no-poster image appear and leads to below-par user experience.

**Steps to Reproduce for person objects:**
1. Search the term 'Bruce Willis' in search bar of application
2. View Displayed results
3. Observe an imageless thumbnail with the name undefined in the results
4. click the undefined thumbnail
5. Get 404 error

**Expected Behavior:**
- I expect to be able to see additional information on the displayed results, in order to distinguish between 2 or more titles of the same name when neither of them have a unique image.
- I expect to not see person data as part of search results

**Additional Information:**
- **Assignee:** @germagla 
- **Relevant Screenshots:**
1.
<img width="935" alt="Screen Shot 2023-09-25 at 8 51 31 AM" src="https://github.com/gm-io/spoilers/assets/16067623/67b8a992-c740-40fc-85eb-8464e62be946">
2. 
<img width="941" alt="Screen Shot 2023-09-25 at 8 55 11 AM" src="https://github.com/gm-io/spoilers/assets/16067623/94ccdf00-b5ba-428e-ac79-47de429fa010">
3.
<img width="1048" alt="Screen Shot 2023-09-25 at 9 05 34 AM" src="https://github.com/gm-io/spoilers/assets/16067623/77e6e02b-7e19-4d56-9384-c5cf1d8508e7">

**Comment by germagla** [comment]
Removed 'person' objects. Now the issue I have is the external api does not return such details on the search endpoint. A few workarounds I have in mind, in no particular order:

- #### Make a zillion requests:

I can make an external get request for each returned object (async, so it's not too slow) and add a director key to each object. One problem with this is that we will be firing so many requests at the external API that we might get timed out sometimes. Their limits are somewhat vague.

- #### Display a details card on hover:

We could make it so that when a user hovers over a result, a small 'details' card shows, with a bit more info about the hovered entry. This component would use our internal movie/tv details endpoint.



I will edit this comment if I think of something else, let me know what you think.

**Comment by germagla** [comment]
>temp solution: no poster, not returned, return 20 entries regardless (query next pages until number is met)
